apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: previewdtestserver
  name: previewdtestserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: previewdtestserver
  template:
    metadata:
      labels:
        app: previewdtestserver
    spec:
      containers:
        - image: registry.hub.docker.com/clarkezone/previewd:0.0.4
          imagePullPolicy: IfNotPresent
          name: previewd
          env:
            - name: PORT
              value: "8080"
            - name: LOGLEVEL
              value: "debug"
          ports:
            - containerPort: 8080
              protocol: TCP
