apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: previewdtestserver
      name: previewd-service
    spec:
      ipFamilies:
        - IPv4
      ports:
        - name: 8090-8080
          port: 8090
          targetPort: 8080
      selector:
        app: previewdtestserver
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
