kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blogrender-pvc
  namespace: previewdtest
  labels:
    app: previewdtest
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
