apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: previewd-rb
  namespace: previewdtest
  labels:
    app: previewdtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: previewd-role
subjects:
  - kind: ServiceAccount
    name: previewd-sa
